; Auto-generated by scripts/generate-nsis-installer-assets.js — do not edit.
; Relative to makensis cwd (app-builder-lib/templates/nsis). Copied by generate-nsis-installer-assets.js.
!undef MUI_WELCOMEFINISHPAGE_BITMAP
!undef MUI_UNWELCOMEFINISHPAGE_BITMAP
!define MUI_WELCOMEFINISHPAGE_BITMAP "calllog-wizard-sidebar.bmp"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "calllog-wizard-sidebar.bmp"
